### ISSUE TITLE
empty div is left after a form submission

### ISSUE THREAD

**Issue by buduguru** [meteor-useraccounts/semantic-ui#10]
After the default form (template atForm) is submitted, it disappears but the empty div of class `at-form ui large fluid form segment` is left in its place though nothing should be left. You can check this out on my web http://studycz.meteor.com (the form is on frontpage).

**Comment by splendido** [comment]
Unfortunately that's the current behaviour...
If you add `splendido:accounts-meld` and turn on the configuration parameter `showAddRemoveServices` you should see something though...

You might want to wrap `atForm` inside an if clause like this:

```handlebars
{{#unless currentUser}}
  {{> atForm}}
{{/unless}}
```
