### ISSUE TITLE
Optional checkbox style

### ISSUE THREAD

**Issue by dalgard** [meteor-useraccounts/semantic-ui#11]
When doing a checkbox, the toggle style widget from Semantic UI is used (the element has a `toggle` class). I think it is quite a presumption, using that style as the default – please consider changing it.

In the meantime, how can I render the form with a normal style checkbox? Will I have to hack it via a `rendered` hook?

**Comment by dalgard** [comment]
To answer my last question, I think the best way is with the [template-extension](https://github.com/aldeed/meteor-template-extension) package. All helpers and events are inherited – it works like this:

```html
<template name="myAtCheckboxInput">
  <div class="at-input inline field">
    <div class="ui checkbox">
      <input type="{{type}}" id="at-field-{{_id}}" name="at-field-{{_id}}" {{disabled}}>
      <label for="at-field-{{_id}}">{{displayName}}</label>
    </div>
  </div>
</template>
```

```javascript
Template.myAtCheckboxInput.replaces("atCheckboxInput");
```

**Comment by splendido** [comment]
Yeah, that's the quicker solution...

In principle it wouldn't be difficult to add some other configuration options to select the checkbox style...
...but this would be hard to work for all availble front-end.

@meteor-useraccounts/semantic-ui, what do you think?
Should we change the default style to the *normal* checkbox?

We might also think about adding front-end-specific options, but I'd keep this reasoning for the v2.0 milestone.

**Comment by dalgard** [comment]
It would be nice to have a property for `addField` – like `custom:` – which could be an object that is passed on to the templates.

Right now I'm looking into getting extra options that I set on my fields into the templates. For instance, I would like to be able to tell the template to put a divider before this or that field or to make a field 50 % width.

**Comment by splendido** [comment]
How would you like the whole thing to be?

...for the divider I think we could make it to add a *special* field type `divider`.
Feel free to make a PR about this, I'll accept it without concerns...

for the width, and in general for the layout, it might be trickier to achieve.
But, again, we can discuss this and see if there's a way to put it in a simple way adding another few configuration options.

**Comment by dalgard** [comment]
Before going any further, I wonder whether there are any bad implications of having an `options` (or similarly named) property that is passed on to the templates untouched?

The names of the various options, as long as they only relate to layout and such, might be chosen freely by different UIs – including custom options for when a developer is using template overrides, e.g. with the [template-extension](https://github.com/aldeed/meteor-template-extension) package.

Something like a divider consists either of additional markup (like an `<hr>`) or a special class – it should be up to the UI of choice.

(P.S. Should we move this discussion to the core repo?)

**Comment by splendido** [comment]
Yeah, I think it is better to continue on the core repo.

P.S. I'm not following what you mean with `options`. Some additional classes to be added to the form elements?

At the moment all the templates for the input fields, for example, are defined [here](https://github.com/meteor-useraccounts/unstyled/blob/master/lib/at_input.html).
The separator might be simply another templated shaped as needed for each framework...
