### ISSUE TITLE
No 'loginButtons' template found after adding this package to my project

### ISSUE THREAD

**Issue by lsunsi** [meteor-useraccounts/semantic-ui#16]
I have accounts-password already in my package.
If I try installing accounts-ui too, it works but the login is unstyled. (or styled with the default accounts-ui style).

Is this a bug or am I doing something wrong?

**Comment by splendido** [comment]
Hello @lsunsi,
this package is not supposed to be used together with `accounts-ui` and I strongly suggest not to do it.

The template you should be using is `atForm`.
You can have a look at some example app among the [boilerplates](https://github.com/meteor-useraccounts/boilerplates).

Let me know in case you need more help!

**Comment by lsunsi** [comment]
Is there some documentation on this?
I've look for a long before posting it here.
Maybe I'm not that smart. haha.

Also, if I'm including the login buttons in a menu-navbar (like with accounts-ui), should I use the atForm template also?

**Comment by splendido** [comment]
you can have a look at the [Guide](https://github.com/meteor-useraccounts/core/blob/master/Guide.md) even if it could got messed up a bit with time...

for the nav bar there's the `atNavButton` template which provides very basic routing abilities...
Lets checkout the [Routing](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#routing) section to get started with this...

**Comment by lsunsi** [comment]
Okay, I see.
So the create account/login by dropdown isn't possible, right?
Just the full page login form.

I guess that will have to do. haha.

**Comment by splendido** [comment]
for the dropdown you'll have to head toward `accounts-ui` ;-)
