### ISSUE TITLE
The links dont work

### ISSUE THREAD

**Issue by Narven** [meteor-useraccounts/semantic-ui#18]
the links for the learn more and live application on this page dont work:

[https://atmospherejs.com/useraccounts/semantic-ui](https://atmospherejs.com/useraccounts/semantic-ui)

Are they just broken.. or actualy dont exist?

**Comment by splendido** [comment]
Good catch @Narven!
The correct links are
* http://useraccounts.meteor.com/
* http://useraccounts-semantic-ui.meteor.com/

Let me fix them!
