### ISSUE TITLE
Drop 'large' class from form segment

### ISSUE THREAD

**Issue by dalgard** [meteor-useraccounts/semantic-ui#19]
Around Semantic UI version 1.12, the font size of input fields was changed to relative units (as they were intended), which makes the fields on the `at-form` look oversized, due to the element's `large form segment` class.

I suggest the `large` class is dropped, since the markup would be more neutral without it.

**Comment by splendido** [comment]
makes sense @dalgard!
Could you please create a PR for this?

**Comment by dalgard** [comment]
Will do it after the weekend.

**Comment by lumatijev** [comment]
Hey. You don't need to do it. I'll make PR later today for updated design. Matching Semantic UI 2.

**Comment by splendido** [comment]
:+1:

**Comment by dalgard** [comment]
Great. What do you propose to do in regard to version number?

It is kind of a breaking change, since an update would change the look of the form – unless the whole project isn't upgraded to Semantic UI 2.0, which is much too much to ask. So, in that respect the major version should be bumped.

On the other hand, upgrading this package to 2.0 would falsely signal compatibility with the next version of `useraccounts`, rather than Semantic UI...

**Comment by splendido** [comment]
What about bumping the minor version and update the README to say the package is now up to date with SUI@2.0?

useraccounts:semantic-ui@2.0 will defenitely be used when all useraccounts packages will bump to 2.0.
After that I expect single packages to bump on need and not like now all together...

**Comment by lumatijev** [comment]
Agree with @splendido. That would make more sense due to `useraccounts` package version.

Just made PR and will wait for @splendido to merge it because I want him to review changes before merge. Look of the form is changed but not drastically.

**Comment by lumatijev** [comment]
@dalgard Did you try to update package? Comment back when you get to see updated design so we can close this issue if you are satisfied. Thank you.

**Comment by splendido** [comment]
Hey guys, I haven't published the new version yet.
I'm waiting to finishe the separation of routing stuff and then I'll bump everything at once.

So, you should use local pacakges to test the latest changes...

**Comment by splendido** [comment]
Closing this, new version being published soon!
