### ISSUE TITLE
Please remove less package dependency

### ISSUE THREAD

**Issue by dbismut** [meteor-useraccounts/semantic-ui#20]
This [less-autoprefixer package](https://github.com/flemay/less-autoprefixer/) by @flemay and handles auto prefix and is therefore a lot more useful than the standard `less` package. Unfortunately, `useraccounts:semantic-ui` **requires** the `less` package, which is incompatible with `less-autoprefixer`.

Here's what the console shows:

```
=> Errors prevented startup:                  
   
   While building the application:
   error: conflict: two packages included in resources, flemay:less-autoprefixer and less,
   are both trying to handle .less
   error: conflict: two packages included in resources, flemay:less-autoprefixer and less,
   are both trying to handle .import.less
```

EDIT: by the way, I think the official `semantic-ui` meteor package dropped the `less` package dependency and recommends to use `flemay:less-autoprefixer`

**Comment by splendido** [comment]
Yeah, I guess turning the [at_semantic-ui.less](https://github.com/meteor-useraccounts/semantic-ui/blob/master/lib/at_semantic-ui.less) into `at_semantic-ui.css` and removing the `less` dependency would be fine!
