### ISSUE TITLE
Do we need a version of this for Semantic UI 2.0?

### ISSUE THREAD

**Issue by shrop** [meteor-useraccounts/semantic-ui#21]
I am not sure what we are missing by not having it at SUI 2.0. Anyway, I have this installed and it seems to work okay so far with my Semantic UI 2.0 setup. Thoughts? Thanks for useraccounts! Very awesome set of packages that the Meteor community now depends on frequently.

**Comment by lumatijev** [comment]
Thanks for the question. It's working correctly with Semantic UI 2. Anyway, I'll make PR for updated design later today. It will match new version design and in my opinion it looks a little bit nicer.

**Comment by shrop** [comment]
Sounds great. Thank you! Appreciate the clarification on it working with 2.

**Comment by lumatijev** [comment]
No problem. Took me some time to create pull request because I just moved to another town and started to work. Sorry if I kept you waiting.
