### ISSUE TITLE
Field missing side border

### ISSUE THREAD

**Issue by sircharleswatson** [meteor-useraccounts/semantic-ui#23]
It seems as though there is a piece missing on these input fields (also on the register form and maybe the other forms as well)

<img width="548" alt="screen shot 2015-08-04 at 10 57 54 pm" src="https://cloud.githubusercontent.com/assets/2199663/9078088/5e15f672-3afc-11e5-8026-1fc3dbf6cdb7.png">

the html for the field by default is set to `<div class="ui labeled icon input">` but according to the semantic-ui docs, for a field like this, it should be `<div class="ui *corner* labeled icon input">`

I tried looking but wasn't sure where to find this in the code, otherwise I'd create a PR for it.

**Comment by lumatijev** [comment]
What version of this package and Semantic UI do you use?

**Comment by sircharleswatson** [comment]
@lumatijev I just added it to my project yesterday, so the latest of each. Whatever is on Atmosphere.

**Comment by nooitaf** [comment]
@sircharleswatson, `semantic:ui` or `semantic:ui-css` ? Or maybe post `meteor list` results?

**Comment by sircharleswatson** [comment]
`semantic:ui@2.0.7` and `useraccounts:semantic-ui@1.0.1`

**Comment by lumatijev** [comment]
You are using old version. Try `meteor update` to get newest version available, which is 1.11.1 at the moment.

**Comment by sircharleswatson** [comment]
@lumatijev Thanks. that's really weird that it didn't give me the most recent version when I added it to my project. I literally added it 2 days ago so I don't understand why it gave me an old version.

Either way, I just updated and it still has the issue with the side border missing. it needs that `corner` class like I mentioned

**Comment by lumatijev** [comment]
We need to wait for @splendido to publish latest version. If you are in hurry with your work you can download this package and install it as local package.

###### Short instructions if you never did that before.

1. `meteor remove useraccounts:semantic-ui`
2. extract downloaded file to your project path in `packages` directory
3. `meteor add useraccounts:semantic-ui`

That way you will install local package. And when new version is published you can safely remove it with `meteor remove`, delete local package directory (or whole packages directory) and install it again as usual.

**Comment by sircharleswatson** [comment]
I'm not in a hurry :) Just wanted to make sure I wasn't going crazy. I can wait for the update.

**Comment by splendido** [comment]
Can we close this?

**Comment by abernix** [comment]
This issue can probably be closed.  Using the correct version *does* fix the problem, but as @sircharleswatson mentioned, for some reason when you install the packages initially, it does choose `1.0.1` as the version by default sometimes.  If you force add it as `meteor add useraccounts:semantic-ui@1.12.3` then the problem goes away entirely.

**Comment by sircharleswatson** [comment]
I haven't verified but I trust you guys. I'll close this!

**Comment by splendido** [comment]
Could you please open a new issue on the core repo if you still get problems with version selection?
