### ISSUE TITLE
Live demo not working

### ISSUE THREAD

**Issue by ankitgaurav** [meteor-useraccounts/semantic-ui#26]
Please host the live demo somewhere other than *.meteor.com
The meteor free hosting has come to an end.

**Comment by venetianthief** [comment]
See https://github.com/meteor-useraccounts/core/issues/660

**Comment by splendido** [comment]
@stubalio is now investigating about this. See this [issue comment](https://github.com/meteor/guide/issues/409#issuecomment-215911961)
